name: PDFQuickFix
options:
  minimumXcodeGenVersion: 2.38.0
  lastUpgradeCheck: 1600
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    SWIFT_VERSION: 5.9
packages: {}
targets:
  PDFQuickFix:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources/PDFQuickFix
    info:
      path: Sources/PDFQuickFix/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: PDFQuickFix
        CFBundleDisplayName: PDFQuickFix
        CFBundleVersion: 1
        CFBundleShortVersionString: 0.2.0
        LSApplicationCategoryType: public.app-category.productivity
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    entitlements:
      path: Sources/PDFQuickFix/PDFQuickFix.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true
    settings:
      base:
        CODE_SIGNING_ALLOWED: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.yordamkocatepe.PDFQuickFix
        SWIFT_OBJC_BRIDGING_HEADER: Sources/PDFQuickFix/Bridging-Header.h
        ASSETCATALOG_COMPILER_APPICON_NAME: PDFQuickFixIcon
  PDFQuickFixTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Tests/PDFQuickFixTests
    dependencies:
      - target: PDFQuickFix
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
